### ISSUE TITLE
on rg351 it seems only R2 and L2 are not working

### ISSUE THREAD

**Issue by navy1978** [lualiliu/RG351P_virtual-gamepad#1]
on RG351 the R2 and L2 buttons are not working I tried all types of output joypad with no effects 

The output joypad that works partially is the oga_joypad but as said L2 and R2 dont work....

`/usr/bin/rg351p-js2xbox -t oga_joypad`

Can you please exaplain how to fix this issue?

**Comment by lualiliu** [comment]
Which model of RG351 are you referring to? Maybe I can try to fix it.

**Comment by navy1978** [comment]
Forget I made it work my mistake sorry !
